### ISSUE TITLE
RuntimeError: shape '[2, 37, 3, 12, 66]' is invalid for input of size 176712

### ISSUE THREAD

**Issue by Yulv-git** [microsoft/vision-longformer#1]
When add some code to use the MsViT model in src/models/msvit.py  as follow:
`
if __name__ == "__main__":
    test_tensor = torch.randn(2, 3, 384, 384)
    net = MsViT(num_classes=122, img_size=384, drop_rate=0., drop_path_rate=0.1, norm_embed=True, avg_pool=False,
                    arch='l1,h3,d192,n1,s1,g1,p16,f7,a1_l2,h6,d384,n10,s0,g1,p2,f7,a1_l3,h12,d796,n1,s0,g1,p2,f7,a1', sharew=True,
                    attn_type='longformerhand',
                    share_kv=True, only_glo=False, sw_exact=0, ln_eps=1e-6, mode=0)
`
the following error occurred in src/models/msvit.py line 87.

`RuntimeError: shape '[2, 37, 3, 12, 66]' is invalid for input of size 176712`

Can you help me? Thank you very much!

**Comment by pzzhang** [comment]
In the last stage, you specify 'l3,h12,d796,n1,s0,g1,p2,f7,a1', in which 796 cannot divided by 12. This causes the error. I guess that you may want to set 'l3,**h12,d768**,n1,s0,g1,p2,f7,a1'

**Comment by Yulv-git** [comment]
Thanks very much!
